version: '3'

services:
  frontend:
    image: baniomash1/node_web_nuvem:latest
    ports:
      - '8080:3000'
    container_name: 'frontend'
    command: sh -c "git pull origin master && npm install && npm start"

  backend:
    image: baniomash1/web_nuvem_backend:latest
    ports:
      - '5000:5000'
    container_name: 'backend'
    command: sh -c "git pull origin master && npm install && npm start"

  pgsql:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: 'pgsql'
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword

volumes:
  pg-data: